### ISSUE TITLE
file not found!

### ISSUE THREAD

**Issue by MaheshBabu11** [Eternal-Soul-786/Text-Based-Classification-on-Bullying-Content#1]
![197f1a20-3447-4f08-957b-82a674ea0dd2](https://user-images.githubusercontent.com/43287976/81260566-e2368600-9057-11ea-9f6b-023a1b683c24.jpg)
 

please provide the specified file

**Comment by Eternal-Soul-786** [comment]
now check it i have uploaded the folder kol.
